Repository EYBlockchain/nightfish_CE, pull requests merged in 2025-08, with the labels that each got.

#68 Jiajie/support 256
  plonk/src/recursion/mod.rs
Labels: enhancement

#77 feat: sparse MLE in-circuit evaluation
  plonk/src/nightfall/circuit/plonk_partial_verifier/poly.rs
Labels: enhancement

#87 fix: constrain pi_hash to be equal to the instance used in `reconstruct_mle_challenges`
  plonk/src/recursion/circuits/challenges.rs
  plonk/src/recursion/circuits/mle_arithmetic.rs
  plonk/src/recursion/merge_functions.rs
Labels: security

#90 fix: emphasise SRSs for KZG and IPA are fixed
  plonk/src/nightfall/hops/univariate_ipa.rs
  plonk/src/nightfall/mle/zeromorph/zeromorph_protocol.rs
  primitives/src/pcs/univariate_kzg/mod.rs
Labels: documentation, enhancement

#56 insert sha256 hash
  plonk/src/recursion/merge_functions.rs
  plonk/src/recursion/mod.rs
Labels: DNM, do not review
